apiVersion: v1
kind: Pod
metadata:
  name: post-demo1
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - name: webport
      containerPort: 80
    lifecycle:
      postStart:
        exec: 
          command: ["/bin/sh", "-c", "echo post start here > /usr/share/message"]    
